public enum MessageHintType
{
    none,
    ClosedFromInside,
    GoFindMagicBowl,
    WrongBooks01,
    WrongBooks02,
    WrongBooks03,
    WrongBooks04,
    WrongBooks05,
    WrongBooks06,
    WrongBooks07,
    WrongBooks08,
    WrongBooks09,
    WrongBooks10,
    LetsDrinkElixir,
    YouHaveShrunk,
    RatAlert
}
